# DESLABS FRONTPAGE

replicaCount: 1
namespace: 'deslabs'

ingress:
  class: "deslabs"
  ssl: "false"

image:
  uid: 1001
  gid: 1001
  repository: mgckind/frontpage
  tag: "2.4.0"
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 80
