# DESLABS FRONTPAGE
name: frontpage
version: "2.4.0"

replicaCount: 2
namespace: 'deslabs-devel'

ingress:
  class: "deslabs-devel"
  ssl: "false"

image:
  uid: 1001
  gid: 1001
  repository: localhost:5000/deslabs-frontpage
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 80
