# DESLABS FRONTPAGE

replicaCount: 2
namespace: 'deslabs'

ingress:
  class: "deslabs"
  ssl: "false"

image:
  uid: 1001
  gid: 1001
  repository: mgckind/frontpage
  tag: 2.3.13
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 80
