# DESLABS FRONTPAGE
name: frontpage-dev
version: "2.4.0"

replicaCount: 2
namespace: 'deslabs'

ingress:
  class: "deslabs-dev"
  ssl: "false"

image:
  uid: 1001
  gid: 1001
  repository: mdjohnson/deslabs-frontpage
  tag: "2.4.0"
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 31000
