# DESACCESS JUPYTER LAB SERVER
#
namespace: 'deslabs'
replicas: 2


# Only one should be enabled
storage:
  local:
    enabled: true
    type: local
    className: manual
    path: "/des004/deslabs/jhub"
    #path: "/home/matias/kubedata/external/jhub"
  nfs:
    enabled: false
    type: nfs
    className: standard
    server: "10.101.140.143"
    path: "/exports/easyweb/workdir"
  capacity: 150Gi
  access: "ReadWriteMany"


image:
  uid: 1001
  gid: 1001
  repository: "mgckind/lab-server"
  tag: "deslabs"
  pullPolicy: IfNotPresent

mysql:
  secretName: des-labs-mysql
  serviceName: des-labs-mysql
  servicePort:  3306

repositories:
  - "https://github.com/mgckind/dr1_tutorial.git"

service:
  #type: NodePort
  type: ClusterIP
  port: 8888
