apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ printf "%s-%s" .Values.name .Values.version }}
    release: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      securityContext:
        runAsUser: {{ .Values.image.uid }}
        runAsGroup: {{ .Values.image.gid }}
      initContainers:
        - name: vault-init
          image:  "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          command: ['sh', '-c', 'export VAULT_TOKEN=$(cat .certs/.token.txt | base64 -d) && vault login -no-store token=$VAULT_TOKEN && vault kv get -field desaccess.yaml des/desaccess.yaml | base64 -d > /home/des/des_ncsa/config/desaccess.yaml']
          volumeMounts:
          - name: config-all
            mountPath: "/home/des/des_ncsa/config"
            subPath: "desaccess.yaml"
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Values.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: POD_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.name }}
        volumeMounts:
        - name: config-all
          mountPath: "/home/des/des_ncsa/config"
          subPath: "desaccess.yaml"
      volumes:
      - name: config-all
        emptyDir: {}
