apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Values.namespace }}
  annotations:
    ingress.kubernetes.io/service-upstream: "true"
    ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.ssl }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
   ingress.kubernetes.io/auth-type: basic
   ingress.kubernetes.io/auth-realm: "Auth required"
   ingress.kubernetes.io/auth-secret: htpasswd
spec:
  rules:
  - http:
     paths:
     - path: /
       backend:
         serviceName: "{{ .Chart.Name }}"
         servicePort: {{ .Values.service.port }}

