apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{ (.Files.Glob "/var/jenkins_home/config-data/desncsa-frontpage/config/*").AsSecrets | indent 2 }}
