apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ printf "%s-%s" .Values.name .Values.version }}
    release: {{ .Values.version }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: "{{ .Values.name }}"
