apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Files.Get "config/mysql/root.yaml" | b64enc }}
  admin: {{ .Files.Get "config/mysql/admin.yaml" | b64enc }}
  adminpass: {{ .Files.Get "config/mysql/adminpass.yaml" | b64enc}}
