apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: grafana
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: grafana
        image: grafana/grafana
        volumeMounts:
        env:
        - name: INFLUXDB_HOST
          value: influxdb
        - name: GF_SERVER_HTTP_PORT
          value: "3000" 
        - name: GF_SERVER_ROOT_URL
          value: /status/
        - name: GF_DATA_BASE_TYPE
          value: sqlite3
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_NAME
          value: "DESDM"

