node {
    def app
    env.BUILD_VERSION = divide_build_number()

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */
        dir("github"){
            checkout scm
        }
    }

    stage('Build image') {
        /* This builds the actual image; synonymous to
         * docker build on the command line */

        app = docker.build("mdjohnson/deslabs-frontpage","-f github/deslabs/deslabs-frontpage/Dockerfile .")
    }

    stage('Test image') {
        /* Ideally, we would run a test framework against our image.
         * For this example, we're using a Volkswagen-type approach ;-) */
        app.inside {
            sh 'echo "Tests passed"'
        }
    }

    stage('Push image') {
        /* We'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://registry.hub.docker.com', 'mdjohnson-docker-hub-credentials') {
            app.push("v${env.BUILD_VERSION}")
            app.push("latest")
        }
    }


   stage('Create Helm templates') {
        /* We'll create deployment yaml from Helm */
        dir('github/deslabs/deslabs-frontpage'){
            sh "helm template frontpage --set image.tag=v${env.BUILD_VERSION}> deploy_frontpage.yaml" 
            sh "mv deploy_frontpage.yaml ${env.WORKSPACE}/bitbucket/frontpage"
    }
    }

    stage('Commit deploy_frontpage.yaml to bitbucket repository') {
        /* Let's make sure we have the repository cloned to our workspace */
      dir('bitbucket'){  git branch: 'master',
            credentialsId: 'mjohns44-bitbucket-credentials',
            url: 'https://opensource.ncsa.illinois.edu/bitbucket/scm/desdm/deslabs-deploy.git'
        
            sh "mv ${env.WORKSPACE}/github/deslabs/deslabs-frontpage/deploy_frontpage.yaml ."
            sh "git commit -am v${env.BUILD_VERSION}"

        }
    }

}

def divide_build_number(){
    node {
        build_version = env.BUILD_NUMBER.toLong() / 100.0
        build_version_float = build_version.toFloat()
        return String.format("%.2f",build_version_float)
    }
}
