# DESACCESS
#
namespace: 'deslabs'

replicaFront: 1
replicaWorkers: 1
replicaBulkWorkers: 1
replicaMonitor: 1

ingressFront:
  class: "deslabs"
  ssl: "false"

ingressMonitor:
  class: "deslabs"
  ssl: "false"

commands:
  front:
    - "python"
    - "/home/des/desaccess/deslabs.py"
  workers:
    - "/bin/bash"
    - "-c"
    - "celery worker  -A ea_tasks  -E -Ofair --loglevel=info"
  bulkworkers:
    - "/bin/bash"
    - "-c"
    - "celery worker  -A ea_tasks  -E -Ofair --loglevel=info -Q bulk-queue"
  monitor:
    - "/bin/bash"
    - "-c"
    - "flower -A ea_tasks  --url_prefix=flower"

tilespath: "/home/matias/DES/dr1_tiles"

# Only one should be enabled
storage:
  local:
    enabled: true
    type: local
    className: manual
    #path: "/des004/deslabs/easyweb/workdir"
    path: "/home/matias/kubedata/external/easyweb/workdir"
  nfs:
    enabled: false
    type: nfs
    className: standard
    server: "10.101.140.143"
    path: "/exports/easyweb/workdir"
  capacity: 1500Gi
  access: "ReadWriteMany"



image:
  uid: 1001
  gid: 1001
  repository: mgckind/desaccess
  tag: deslabs-rc1
  pullPolicy: IfNotPresent

serviceFront:
  type: NodePort
  #type: ClusterIP
  port: 8080

serviceMonitor:
  type: NodePort
  #type: ClusterIP
  port: 5555
