# DESACCESS
#
namespace: 'default'

replicaFront: 2
replicaWorkers: 4
replicaMonitor: 1

ingressFront:
  class: "nginx"
  ssl: "false"

ingressMonitor:
  class: "nginx"
  ssl: "false"

commands:
  front:
    - "python"
    - "/home/des/desaccess/deslabs.py"
  workers:
    - "/bin/bash"
    - "-c"
    - "celery worker  -A ea_tasks   -E -Ofair --loglevel=info"
  monitor:
    - "/bin/bash"
    - "-c"
    - "flower -A ea_tasks  --url_prefix=flower"


# Only one should be enabled
storage:
  local:
    enabled: false
    type: local
    className: manual
    path: "/home/matias/kubedata/external/easyweb/workdir"
  nfs:
    enabled: true
    type: nfs
    className: standard
    server: "10.101.140.143"
    path: "/exports/easyweb/workdir"
  capacity: 1500Gi
  access: "ReadWriteMany"



image:
  uid: 1001
  gid: 1001
  repository: mgckind/desaccess
  tag: deslabs-dev
  pullPolicy: IfNotPresent

serviceFront:
  type: NodePort
  #type: ClusterIP
  port: 8080

serviceMonitor:
  type: NodePort
  #type: ClusterIP
  port: 5555
