apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-front"
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Chart.Version }}
spec:
  type: {{ .Values.serviceFront.type }}
  ports:
  - port: {{ .Values.serviceFront.port }}
  selector:
    app: "{{ .Chart.Name }}-front"
