# MYSQL
replicaCount: 1
namespace: 'deslabs'


# Only one should be enabled
storage:
  local:
    enabled: true
    type: local
    className: manual
    path: "/des004/deslabs/mysql"
  nfs:
    enabled: false
    type: nfs
    className: standard
    server: "10.101.140.143"
    path: "/exports/mysql"
  capacity: 30Gi
  access: "ReadWriteMany"
  

image:
  uid: 1001
  gid: 1001
  repository: mysql
  tag: 5.7
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 3306
