kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  labels:
    type: {{ .Values.storage.type }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Chart.Version }}
spec:
  storageClassName: {{ .Values.storage.className }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - {{ .Values.storage.access }}
  hostPath:
    path: {{ .Values.storage.path }}
