# DEFAULT BACKEND

replicaCount: 1
namespace: 'nginx-ingress'

image:
  repository: gcr.io/google_containers/defaultbackend
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 80
  targetPort: 8080
