apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "{{ .Values.name }}"
  namespace: {{ .Values.namespace }}
  annotations:
    #nginx.ingress.kubernetes.io/service-upstream: "true"
    #nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.ssl }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
  - http:
     paths:
     - path: /
       backend:
         serviceName: "{{ .Values.name }}"
         servicePort: {{ .Values.service.port }}
