apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version }}
    release: {{ .Chart.Version }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}
