# REDIS

replicaCount: 1
namespace: 'default'

# Only one should be enabled
storage:
  local:
    enabled: false
    type: local
    className: manual
    path: "/home/matias/kubedata/external/redis"
  nfs:
    enabled: true
    type: nfs
    className: standard
    server: "10.101.140.143"
    path: "/exports/redis"
  capacity: 150Gi
  access: "ReadWriteMany"


image:
  uid: 1000
  gid: 1000
  repository: redis
  tag: 4.0
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 6379
