# DES-NCSA Website
# des.ncsa.illinois.edu
#
name: desncsa-main
version: "0.0.0"
namespace: 'deslabs-devel'

replicaCount: 1

ingress:
  class: "internal"
  ssl: "true"

image:
  uid: 1001
  gid: 1001
  repository: mdjohnson/desncsa-frontpage
  tag: "0.0.0"
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 8080

initContainer:
  image: mdjohnson/vault-init
  tag: latest
