# DES-NCSA Website
# des.ncsa.illinois.edu
#
name: desncsa-main 
namespace: 'despublic'
version: "2.4.0"

replicaCount: 3

ingress:
  class: "nginx"
  ssl: "true"

image:
  uid: 1001
  gid: 1001
  repository: mdjohnson/desncsa-frontpage
  tag: "2.4.0"
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 8080
