# DES-NCSA Website
# des.ncsa.illinois.edu
#
namespace: 'default'

replicaCount: 1

ingress:
  class: "internal"
  ssl: "true"

image:
  uid: 1001
  gid: 1001
  repository: mgckind/des-ncsa
  tag: y1-dev1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  #type: ClusterIP
  port: 8080
