# Default values for des-labs-mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: 'default'

ingress:
  class: "nginx"
  ssl: "false"

image:
  uid: 1001
  gid: 1001
  repository: mgckind/frontpage
  tag: 2.3.13
  pullPolicy: IfNotPresent

service:
  #type: NodePort
  type: ClusterIP
  port: 80
